#!/usr/bin/env bash

. "$HOME/.fx/bash/config/develop/colors.bash"

update-hopp() {
    local url='https://github.com/hoppscotch/agent-releases/releases/latest/download/Hoppscotch_Agent_linux_x64.AppImage'
    local file="$HOME/apps/hopp.agent"
    local error=''

    { error=$(curl -fL "$url" -o "$file" 2>&1 1>&3 | tee /dev/fd/3 | grep "^curl:"); } 3>&1
    [[ -n "$error" ]] && {
        echo -en "\033[1A"
        cecho "<error>[error]</> ->$(cut -d ':' -f2- <<< "$error")"
        return 1
    }
    
    chmod +x "$file"
    cecho "<g>✓ done!"
}

(return 2>/dev/null) || { 
    update-hopp; 
}
